spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${POSTGRES_DB}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.datasource.hikari.data-source-properties.sslmode=require

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}

tms.app.jwtSecret=${JWT_SECRET}
tms.app.jwtExpirationMs=86400000